-- DROP TABLE "SYSTEM"."ST_SPATIAL_REFERENCE_SYSTEMS_COPY";

-- Create a SYSTEM copy table with the same structure as SYS.ST_SPATIAL_REFERENCE_SYSTEMS
CREATE ROW TABLE "SYSTEM"."ST_SPATIAL_REFERENCE_SYSTEMS_COPY" (
	"OWNER_NAME" NVARCHAR(256) CS_STRING,
	"SRS_ID" INT CS_INT,
	"SRS_NAME" NVARCHAR(256) CS_STRING,
	"ROUND_EARTH" NVARCHAR(256) CS_STRING,
	"AXIS_ORDER" NVARCHAR(256) CS_STRING,
	"SNAP_TO_GRID" DOUBLE CS_DOUBLE,
	"TOLERANCE" DOUBLE CS_DOUBLE,
	"SEMI_MAJOR_AXIS" DOUBLE CS_DOUBLE,
	"SEMI_MINOR_AXIS" DOUBLE CS_DOUBLE,
	"INV_FLATTENING" DOUBLE CS_DOUBLE,
	"MIN_X" DOUBLE CS_DOUBLE,
	"MAX_X" DOUBLE CS_DOUBLE,
	"MIN_Y" DOUBLE CS_DOUBLE,
	"MAX_Y" DOUBLE CS_DOUBLE,
	"MIN_Z" DOUBLE CS_DOUBLE,
	"MAX_Z" DOUBLE CS_DOUBLE,
	"MIN_M" DOUBLE CS_DOUBLE,
	"MAX_M" DOUBLE CS_DOUBLE,
	"ORGANIZATION" NVARCHAR(256) CS_STRING,
	"ORGANIZATION_COORDSYS_ID" INT CS_INT,
	"SRS_TYPE" NVARCHAR(256) CS_STRING,
	"LINEAR_UNIT_OF_MEASURE" NVARCHAR(256) CS_STRING,
	"ANGULAR_UNIT_OF_MEASURE" NVARCHAR(256) CS_STRING,
	"POLYGON_FORMAT" NVARCHAR(256) CS_STRING,
	"STORAGE_FORMAT" NVARCHAR(256) CS_STRING,
	"DEFINITION" NVARCHAR(256) CS_STRING,
	"TRANSFORM_DEFINITION" NVARCHAR(256) CS_STRING
);


-- And copy all the data.
INSERT INTO ST_SPATIAL_REFERENCE_SYSTEMS_COPY(
	"OWNER_NAME",
	"SRS_ID",
	"SRS_NAME",
	"ROUND_EARTH",
	"AXIS_ORDER",
	"SNAP_TO_GRID",
	"TOLERANCE",
	"SEMI_MAJOR_AXIS",
	"SEMI_MINOR_AXIS",
	"INV_FLATTENING",
	"MIN_X",
	"MAX_X",
	"MIN_Y",
	"MAX_Y",
	"MIN_Z",
	"MAX_Z",
	"ORGANIZATION",
	"ORGANIZATION_COORDSYS_ID",
	"SRS_TYPE",
	"LINEAR_UNIT_OF_MEASURE",
	"ANGULAR_UNIT_OF_MEASURE",
	"POLYGON_FORMAT",
	"STORAGE_FORMAT",
	"DEFINITION",
	"TRANSFORM_DEFINITION"
)
SELECT 
	"OWNER_NAME",
	"SRS_ID",
	"SRS_NAME",
	"ROUND_EARTH",
	"AXIS_ORDER",
	"SNAP_TO_GRID",
	"TOLERANCE",
	"SEMI_MAJOR_AXIS",
	"SEMI_MINOR_AXIS",
	"INV_FLATTENING",
	"MIN_X",
	"MAX_X",
	"MIN_Y",
	"MAX_Y",
	"MIN_Z",
	"MAX_Z",
	"ORGANIZATION",
	"ORGANIZATION_COORDSYS_ID",
	"SRS_TYPE",
	"LINEAR_UNIT_OF_MEASURE",
	"ANGULAR_UNIT_OF_MEASURE",
	"POLYGON_FORMAT",
	"STORAGE_FORMAT",
	"DEFINITION",
	"TRANSFORM_DEFINITION"
FROM SYS.ST_SPATIAL_REFERENCE_SYSTEMS;


-- Grant access to your app user.
GRANT SELECT ON ST_SPATIAL_REFERENCE_SYSTEMS_COPY TO MY_APP_USER1
